apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage }}
    storageClassName: standard-rwo
