apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secret
type: Opaque
data:
  DATABASE_USER: Y2hhdGJvdA==  # chatbot (base64)
  DATABASE_PASSWORD: Y2hhdGJvdDEyMw==  # chatbot123 (base64)
  GEMINI_API_KEY: QUl6YVN5Q0ItY0N0R3ZwWE5ycGRQRUJITGVFVGI0WmZEb0E1VXBZ  # AIzaSyCB-cCtGvpXNrpdPEBHLeETb4ZfDoA5UpY (base64)