apiVersion: v2
name: chatbot
description: A Chatbot with RAG functionality
type: application
version: v1.0.62
appVersion: "v1.0.62-fda05176"
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
